### ISSUE TITLE
Using the authorization between different sessions.

### ISSUE THREAD

**Issue by Marc008** [divinity76/hhb_.inc.php#13]
Hello,

Pretty cool your library. I was wondering if it possible to store the authorization granted and then, use it between different sessions.

I have added to `_setComfortableOptions()` the values:
`CURLOPT_COOKIESESSION => true,
				CURLOPT_COOKIEJAR => dirname(__FILE__).'/../../cookies/test.txt',
				CURLOPT_COOKIEFILE => dirname(__FILE__).'/../../cookies/test.txt',`

But it isn't working.

I'm trying to use it to the double factor verification. If I put all the code in one single file and execute everything from there (setting the SMS code previously from the Android app login generator code). It works perfectly, but if I separate the code in two files, first call the one that sends the SMS and then setting that SMS and executing the rest of the code... It doesn't work.

Any idea about how to keep the session between different calls?

**Comment by Marc008** [comment]
It looks like I was missing the referrer, once I configured, it worked.

Great lib!

**Comment by divinity76** [comment]
thanks :)
ps, instead of editing _setComfortableOptions(), you could do

```php
$hc->setopt_array ( array (
		CURLOPT_COOKIEJAR => dirname ( __FILE__ ) . '/../../cookies/test.txt',
		CURLOPT_COOKIEFILE => dirname ( __FILE__ ) . '/../../cookies/test.txt' 
) );
```
and instead of `dirname(__FILE__)` , you can use `__DIR__` , which does exactly the same (and was added in php 5.3)

**Comment by Marc008** [comment]
Thanks @divinity76 ,

I'll change it.

**Comment by Marc008** [comment]
btw, I don't know what happened but it has stopped working again.
I'm pretty sure the cookie file is working perfectly, but something has to be missed. 

If I put the code generated from the app, it works perfectly, but if I do a different session, then it doesn't work.

**Comment by divinity76** [comment]
stop using `CURLOPT_COOKIESESSION` , just use `CURLOPT_COOKIEJAR` and `CURLOPT_COOKIEFILE` - does that fix the issue?

**Comment by Marc008** [comment]
It does!

Awesome, I'll double check everything to make sure that everything is working and let you know. I can share the later, I'm sure that there are stuffs that can be done better, but it works for now.

**Comment by Marc008** [comment]
It works perfectly, here is the code:

```
$code = '000000';
$url = 'https://twitter.com/account/login_verification';
$authToken = $_SESSION['authToken']; // I get this value from the original form that asks for the code
$challengeId = $_SESSION['challengeId']; // I get this value from the original form that asks for the code
$userId = $_SESSION['userId']; // I get this value from the original form that asks for the code

$inputs = [
    'authenticity_token' => $authToken,
    'challenge_id' => $challengeId,
    'user_id' => $userId,
    'challenge_type' => 'Sms',
    'platform' => 'web',
    'redirect_after_login' => '',
    'remember_me' => true,
    'challenge_response' => $code,
];
$hc = new hhb_curl ( $url, true);
$hc->setopt_array($curlOptions);
$hc->setCookieFile($_SESSION['cookies']); // This are the cookies generated from the original form that asked for the code.
$postCurlOptions = [
    CURLOPT_REFERER => $_SESSION['referrer'], // I get this value from the original form that asks for the code, the value of $hc->getinfo ( CURLINFO_EFFECTIVE_URL );
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => http_build_query ( $inputs ),
    CURLOPT_URL => $url,
];

$hc->setopt_array($postCurlOptions);
$hc->exec();

$html = $hc->getResponseBody ();
echo $hc->getinfo ( CURLINFO_EFFECTIVE_URL )."<br>";
if (stripos($hc->getinfo ( CURLINFO_EFFECTIVE_URL ), 'login/error'))
    echo "SMS Code ERROR<br>";
if (stripos($hc->getinfo ( CURLINFO_EFFECTIVE_URL ), 'login_verification?incorrect_solution=true'))
    echo "Wrong SMS Code<br>";
print_r($html);
```

About the `$hc->setCookieFile($_SESSION['cookies']);`, actualy there is a setCookieFile and a getCookieFile:

```
function setCookieFile($content) {
        if (file_put_contents($this->cookie_file, $content))
            return true;

        return false;
    }

    function getCookieFileContent() {
        curl_close($this->curlh); // Curl handle has to be close before the file is written.

        return file_get_contents($this->cookie_file);
    }

```

the `$this->cookie_file` is created with tempnam at the same time that the other 4 in the __construct and I use it in the _setComfortableOptions by default:

```
function _setComfortableOptions() {
		$this->setopt_array ( array (
				CURLOPT_AUTOREFERER => true,
				CURLOPT_BINARYTRANSFER => true,
				CURLOPT_FOLLOWLOCATION => true,
				CURLOPT_HTTPGET => true,
				CURLOPT_SSL_VERIFYPEER => false,
				CURLOPT_CONNECTTIMEOUT => 4,
				CURLOPT_TIMEOUT => 8,
                CURLOPT_COOKIEJAR => $this->cookie_file,
                CURLOPT_COOKIEFILE => $this->cookie_file, // <<makes curl save/load cookies across requests..
				CURLOPT_ENCODING => "" // << makes curl post all supported encodings, gzip/deflate/etc, makes transfers faster
		) ); //
		return $this;
	}
```
